### ISSUE TITLE
App Store warns about UIWebView deprecation

### ISSUE THREAD

**Issue by aeirola** [terveystalo/react-native-piwik-pro-sdk#28]
Submitting an app that uses the SDK to the Apple App Store triggers a warning stating:

> ITMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

This is due to issues in the underlying native SDK, forcing us to use an older version of the SDK. See https://github.com/PiwikPRO/piwik-pro-sdk-framework-ios/issues/2

**Comment by aeirola** [comment]
There is now a new version of the iOS SDK at https://github.com/PiwikPRO/piwik-pro-sdk-framework-ios/releases/tag/1.0.7 which might fix the issue. Unfortunately they don't provide any changelogs or source code, so it is hard to say what changes are included.

**Comment by DreamEmulator** [comment]
@aeirola will this updated version automatically be incorporated in react-native-piwik-pro-sdk 0.0.30?

**Comment by aeirola** [comment]
@DreamEmulator Unfortunately no, it will require a new version of react-native-piwik-pro-sdk to be released. I'll try to get one out this week though.

**Comment by DreamEmulator** [comment]
@aeirola that would be super, thanks! I kind of temporarily fixed it for our project by raising the module from 1.0.1 to 1.0.7 in the podspec. Seems to be working fine, maybe it's that simple 🙂. Thanks for all the effort on this package, it's very useful.

**Comment by aeirola** [comment]
This is now fixed in version 0.3.1.

Additionally, possible future releases of the Piwik pro SDK pod (https://github.com/PiwikPRO/piwik-pro-sdk-framework-ios) can be updated with `pod update PiwikPROSDK` without needing to update the react-native-piwik-pro-sdk library.
